### ISSUE TITLE
ModuleNotFoundError: No module named 'pyVim'

### ISSUE THREAD

**Issue by shoujche** [waldirio/rvtools#45]
(pyrvtools) shoujche@SHOUJCHE-M-D2AG ~ % rvtools
Traceback (most recent call last):
  File "/Users/shoujche/.pyenv/versions/pyrvtools/bin/rvtools", line 7, in <module>
    from rvtools import rvtools
  File "/Users/shoujche/.pyenv/versions/3.6.6/envs/pyrvtools/lib/python3.6/site-packages/rvtools/rvtools.py", line 9, in <module>
    from pyVim import connect
ModuleNotFoundError: No module named 'pyVim'

i can execute from pyvim import connect, but when execute from pyVim import connect raise the above error.
so why your code use pyVim not pyvim

**Comment by Toxik1983** [comment]
I ran into the same problem, you just need to install [pyvmomi](https://github.com/vmware/pyvmomi) as a dependency.

**Comment by waldirio** [comment]
Hello @Toxik1983 and @shoujche, good morning

Please, feel free to click here https://github.com/waldirio/rvtools_python/releases/tag/1.0.0 and download the binary file. Everything is builtin and will run with no additional configuration of virtual environment and/or python module.

I'll fix this ASAP in order to work fine when installing via pip.

Thank you and sorry for the issue.

**Comment by waldirio** [comment]
Hello @Toxik1983 

Thank you for your heads up and sorry for my delay. Already fixed.
